@Iteration1234
Feature: API EDS Payload Request Response DB Validation

  Scenario Outline: To verify the API EDS service with Payload request , Payload Response and response in DB
    Given EDS Read input from json "<inputfile>" with "<user_name>" and "<proxymessageid>" as header
    When EDS Request is performing "<operation>" on EDS API URL
    And EDS Save response code in xml "<inputrequestfile>"
    Then EDS Verify the value for below xpath elements in "<inputrequestfile>"
      | xpath                                                                                                                                                                                                                                                                           | value                        |
      #| //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResult/BusinessDecisionResultDateTime                                                                               | YYYY-MM-DDThh:mm:ss.SSS      |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResult/BusinessDecisionResultSourceType                                                                             | EnterpriseDecisionService    |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResult/BusinessDecisionResultType                                                                                   | AppraisalAlternative         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/ActiveMLSListingIndicator        | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/AppraisalCompletionAsIsIndicator | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/AppraisalExistenceIndicator      | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/ARMsLengthContractIndicator      | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/DaysOnMarketIndicator            | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/DistressedIndicator              | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/HighestBestUseIndicator          | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/LegalityIndicator                | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/MissingDataIndicator             | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/MultipleListingIndicator         | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/NeighborhoodConformityIndicator  | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/PhysicalDeficiencyIndicator      | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/PropertyAgeCount                 |                           10 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/PropertyConditionIndicator       | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/PublicRecordExistenceIndicator   | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/QualityAgeIndicator              | false                        |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResultDetails/BusinessDecisionResultDetailContainer/PropertyInspectionWaiverResult/QualityIndicator                 | true                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanPropertyCollaterals/LoanPropertyCollateralContainer/LoanPropertyCollateral/FinancedUnitCount                                                                                                                |                            1 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanPropertyCollaterals/LoanPropertyCollateralContainer/LoanPropertyCollateral/PropertyIdentifier                                                                                                                   |                            1 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/Loan/LoanPurposeType                                                                                                                                          | Purchase                     |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/LoanRelationships/LoanRelationship/LoanRoleType                                                                                                               | SubjectLoan                  |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanState/LoanStateDate                                                                                                                                                           | YYYY-MM-DD                   |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanState/LoanStateType                                                                                                                                                           | Current                      |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/AddressContainers/AddressContainer/Address/AddressLineText                                                                                                                         | 1938 TINNIN RD               |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/AddressContainers/AddressContainer/Address/CityName                                                                                                                                | GREELEY                      |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/AddressContainers/AddressContainer/Address/FIPSStateAlphaCode                                                                                                                      | CO                           |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/AddressContainers/AddressContainer/Address/PostalCode                                                                                                                              |                        37072 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyAssessment/PropertyAssessmentSequenceNumber                                                                         |                            1 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyAssessment/PropertyAssessmentSourceType                                                                             | HomeValueService             |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyAssessment/PropertyIdentifier                                                                                       |                            1 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerConfidenceLevelType                                                            | MediumConfidence             |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerForecastStandardDeviationRate                                                  |                         0.16 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerMaximumValueAmount                                                             |                       403250 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerMidPointValueEstimateAmount                                                    |                       432020 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerMinimumValueAmount                                                             |                       294581 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/HomeValueExplorerOptionType                                                                     | HVEFeedback                  |
      #| //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/PropertyValuationEffectiveDateTime                                                              | YYYY-MM-DDThh:mm:ss.SSS      |
     # | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyValuationContainer/PropertyValuation/PropertyValuationAmount                                                                                            |                    200000.00 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyValuationContainer/PropertyValuation/PropertyValuationMethodType                                                                                        | PropertyPresentValuation     |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyValuationContainer/PropertyValuation/PropertyValuationSequenceNumber                                                                                    |                            1 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyValuationContainer/PropertyValuation/PropertyValuationType                                                                                              | Original                     |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ClientSchemaVersionIdentifier                                                                                                                                                                                |                          1.0 |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/EDSSchemaVersionIdentifier                                                                                                                                                                                   |                          1.0 |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/RequestorIdentifier                                                                                                                                                                                          | ACEAPI                       |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ServiceName                                                                                                                                                                                                  | EDSAppraisalAlternativeAPP   |
      #| //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ServiceRequestDateTime                                                                                                                                                                                       | YYYY-MM-DDThh:mm:ss.SSS      |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ServiceRequestIdentifier                                                                                                                                                                                     | EDS must generate UUID       |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ServiceRequestOperationName                                                                                                                                                                                  | evaluateAppraisalAlternative |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/ServiceRequestType                                                                                                                                                                                           | RuleServiceRequest           |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/SubscriberIdentifier                                                                                                                                                                                         | ACEAPI                       |
      | //EnterpriseDecisionService/ServiceRequestContainer/ServiceRequest/SubscriberRequestCorrelationIdentifier                                                                                                                                                                       |                        12345 |
    And EDS Verify the below xpath elements in "<inputrequestfile>" for proxyId
      | xpath                                                                                                                                                                                                                     |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecision/BusinessDecisionIdentifier                                                                   |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResult/BusinessDecisionIdentifier                             |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/BusinessDecisionResult/BusinessDecisionResultIdentifier                       |
      #| //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/PropertyInspectionWaiverResult/BusinessDecisionIdentifier                     |
      #| //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/BusinessDecisions/BusinessDecisionContainer/BusinessDecisionResultContainer/PropertyInspectionWaiverResult/BusinessDecisionResultIdentifier               |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanPropertyCollaterals/LoanPropertyCollateralContainer/LoanPropertyCollateral/LoanIdentifier                                                         |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/Loan/LoanIdentifier                                                                                     |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/LoanAcquisitionContainer/LoanAcquisition/LoanIdentifier                                           |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/LoanApplications/LoanApplicationContainer/LoanApplication/LoanApplicationIdentifier                     |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/LoanStates/LoanStateContainer/LoanDetailContainer/LoanOriginationContainer/LoanOrigination/LoanIdentifier                                                 |
      | //EnterpriseDecisionService/LoanDeliveryStructure/LoanContainer/Properties/PropertyContainer/PropertyValuations/PropertyAppraiserValuationContainer/PropertyValuationAssessment/PropertyValuationAssessmentSequenceNumber |

    Examples: 
      | inputfile      | inputrequestfile  | operation | user_name       | proxymessageid |
      | inputfile1.json | edsapirequest.xml | POST      | webslr1_wksmith | qewd123        |
